### ISSUE TITLE
python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by dataarchivist** [ArchiveTeam/ludios_wpull#19]
Tested on a updated ubuntu 18.04

Collecting wpull
  Downloading https://files.pythonhosted.org/packages/0d/ff/70779b7cb3e25d173df6                                   41e7ae59c20e2597d687ad5e98e36c1429f12a7b/wpull-2.0.1.tar.gz (666kB)
    100% |████████████████████████████████| 675kB 1.2MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ia                                   bqp2w8/wpull/

Any ideas? Thanks!

**Comment by ivan** [comment]
It looks like you're installing wpull and not ludios_wpull. ludios_wpull isn't in pypi.

What were you trying to do and what command did you run?

**Comment by ivan** [comment]
I see that the install instructions in the README were deceptive as they were copied from wpull.

ludios_wpull isn't really intended to be used outside grab-site, but you might be able to install it with:

```
sudo apt-get update
sudo apt-get install --no-install-recommends git build-essential libxml2-dev libxslt1-dev pkg-config
pip install --user --no-binary lxml --upgrade git+https://github.com/ArchiveTeam/ludios_wpull
```

**Comment by dataarchivist** [comment]
I will try it again, may it helps. :)
I just use the readme before posting the issue, btw.
